name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
    - name: Extract ngrok
      run: tar -xvzf ngrok.tgz
    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install OpenSSH Server
      run: sudo apt-get update && sudo apt-get install -y openssh-server
    - name: Configure SSH
      run: |
        sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh
    - name: Set Root Password
      run: echo 'root:P@ssw0rd!' | sudo chpasswd
    - name: Create Tunnel
      run: ./ngrok tcp 22
